# Based on mcdaniel's https://github.com/openedx-actions/tutor-plugin-build-openedx
name: openedx tutor build
description: 'Use Tutor to build a Docker container of openedx and upload it to the GitHub container registry'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  image-name:
    description: 'Name of the image repository in which the newly created container will be uploaded and tagged. Defaults to the name of the repository'
    required: true
  registry-username:
    description: 'Username for the Docker container registry.'
    required: true
  registry-password:
    description: 'Password for the Docker container registry.'
    required: true
  registry-url:
    description: 'URL of the Docker container registry.'
    required: false
    default: 'ghcr.io'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.0.2

    - name: set up Docker Buildx
      id: setup-docker
      uses: docker/setup-buildx-action@v2

    - name: initialize environment variables
      id: init-env
      shell: bash
      run: |
        echo "REPOSITORY_TAG_OPENEDX=$TUTOR_VERSION-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: initialize Docker image URI
      id: init-docker-image
      shell: bash
      run: |
        echo "DOCKER_IMAGE_OPENEDX=${REGISTRY_URL}/${IMAGE_NAME}:${REPOSITORY_TAG_OPENEDX}" >> $GITHUB_ENV
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        REGISTRY_URL: ${{ inputs.registry-url }}

    - name: render tutor config
      id: tutor-config-save
      shell: bash
      run: tutor config save --set DOCKER_IMAGE_OPENEDX=${DOCKER_IMAGE_OPENEDX}

    - name: set tutor-dependent environment variables
      shell: bash
      run: |
        echo "THEMES_PATH=$(tutor config printroot)/env/build/openedx/themes" >> $GITHUB_ENV
        echo "PLUGINS_PATH=$(tutor config printroot)/env/build/openedx/requirements" >> $GITHUB_ENV

    - name: ls the theme folder
      id: ls-theme-folder
      shell: bash
      run: ls $THEMES_PATH -lha

    - name: ls the requirements folder
      id: ls-requirements-folder
      shell: bash
      run: ls $PLUGINS_PATH -lha

    - name: login to GHCR
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    # - name: build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     push: true
    #     tags: ${{ inputs.registry-url }}/${{ inputs.image-name }}:latest

    - name: build the image
      id: tutor-build-image
      shell: bash
      run: |
        tutor images build openedx

    - name: push the image
      id: docker-push-image
      shell: bash
      run: |
        tutor images push openedx
        docker tag ${REGISTRY_URL}/${IMAGE_NAME}:${REPOSITORY_TAG_OPENEDX} ${REGISTRY_URL}/${IMAGE_NAME}:latest
        docker push ${REGISTRY_URL}/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        REGISTRY_URL: ${{ inputs.registry-url }}

    - name: docker image:tag
      id: docker-image
      shell: bash
      run: |
        echo "::set-output name=uri::$(echo $DOCKER_IMAGE_OPENEDX)"
