# Based on mcdaniel's https://github.com/lpm0073/cookiecutter-openedx-devops
name: deploy tutor
description: Github Action to deploy tutor
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  environment-id:
    description: 'The Open edX platform environment. Examples: prod, qa, dev'
    required: true

runs:
  using: "composite"
  steps:
    - name: config DigitalOcean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: LMS_HOSTNAME,CMS_HOSTNAME,DOCKER_IMAGE_OPENEDX,SMTP_EMAIL,${{ secrets.SMTP_PASSWORD }}
        script: |
          # add tutor dir to path
          PATH=$PATH:~/.local/bin
          # config backend variables
          tutor config save \
              --set LMS_HOSTNAME=${LMS_HOSTNAME} \
              --set CMS_HOSTNAME=${CMS_HOSTNAME} \
              --set DOCKER_IMAGE_OPENEDX=${DOCKER_IMAGE_OPENEDX} \
              --set OPENEDX_COMMON_VERSION=open-release/nutmeg.2 \
              --set SMTP_HOST=smtp.porkbun.com \
              --set SMTP_PORT=587 \
              --set SMTP_USE_SSL=false \
              --set SMTP_USE_TLS=true \
              --set SMTP_USERNAME=${SMTP_EMAIL} \
              --set SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
              --set OPENEDX_LMS_UWSGI_WORKERS=8 \
              --set OPENEDX_CMS_UWSGI_WORKERS=4
          # set theme
          tutor local settheme acl-indigo-theme

    - name: print config from DigitalOcean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # pip env
          echo 'pip list:'
          echo '-------------------------------------'
          pip list
          # tutor config apps folder
          echo 'apps:'
          echo '-------------------------------------'
          ls $(tutor config printroot)/env/apps -lha
          # tutor config plugins folder
          if [ ! -d "$(tutor config printroot)/env/plugins" ]; then
            echo "No plugins installed."
            exit
          fi
          echo 'plugins:'
          echo '-------------------------------------'
          ls $(tutor config printroot)/env/plugins -lha
          # tutor config.yml
          echo 'config.yml:'
          echo '-------------------------------------'
          cat -n $(tutor config printroot)/config.yml
          # tutor lms.env.yml
          echo 'lms.env.yml:'
          echo '-------------------------------------'
          cat -n $(tutor config printroot)/env/apps/openedx/config/lms.env.yml
          # tutor cms.env.yml
          echo 'cms.env.yml:'
          echo '-------------------------------------'
          cat -n $(tutor config printroot)/env/apps/openedx/config/cms.env.yml

    - name: deploy tutor via SSH action
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # add tutor dir to path
          PATH=$PATH:~/.local/bin
          # start
          tutor local start -d
