# Based on mcdaniel's https://github.com/lpm0073/cookiecutter-openedx-devops
name: deploy tutor
description: Github Action to deploy tutor
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  environment-id:
    description: 'The Open edX platform environment. Examples: prod, qa, dev'
    required: true

runs:
  using: "composite"
  steps:
    - name: set environment variables
      shell: bash
      run: |
        echo "CONFIG_PATH=$(tutor config printroot)/env/apps/openedx/config" >> $GITHUB_ENV

    # - name: cat settings_merge.yml
    #   shell: bash
    #   run: |
    #     cat -n $GITHUB_WORKSPACE/ci/tutor-deploy/${{ inputs.environment-id }}/settings_merge.yml

    # - name: patch lms.env.yml
    #   shell: bash
    #   run: |
    #     cd ${CONFIG_PATH}
    #     mv lms.env.yml lms.env.yml.orig
    #     yq ea '. as $item ireduce ({}; . * $item )' lms.env.yml.orig  "$GITHUB_WORKSPACE/ci/tutor-deploy/${{ inputs.environment-id }}/settings_merge.yml" >  lms.env.yml

    # - name: patch cms.env.yml
    #   shell: bash
    #   run: |
    #     cd ${CONFIG_PATH}
    #     mv cms.env.yml cms.env.yml.orig
    #     yq ea '. as $item ireduce ({}; . * $item )' cms.env.yml.orig  "$GITHUB_WORKSPACE/ci/tutor-deploy/${{ inputs.environment-id }}/settings_merge.yml" >  cms.env.yml

    # - name: cleanup config folder
    #   shell: bash
    #   run: |
    #     cd ${CONFIG_PATH}
    #     rm *orig

    - name: dump tutor config
      uses: openedx-actions/tutor-print-dump@v0.0.3

    #------------------------------------------------------------------------
    # V. Deploy Open edX
    #------------------------------------------------------------------------
    - name: deploy tutor
      shell: bash
      run: |
        tutor local start

    - name: run tutor init
      shell: bash
      run: |
        tutor local init
